<?xml version="1.0" ?>
<!DOCTYPE templateMetaData [
        <!ELEMENT template (shortDescription|longDescription)*>
        <!ATTLIST template
                active (true|false) #REQUIRED
                major CDATA #REQUIRED
                minor CDATA #REQUIRED
                revision CDATA #REQUIRED
                type IDREF #REQUIRED
                version CDATA #REQUIRED>
        <!ELEMENT shortDescription (#PCDATA)>
        <!ELEMENT longDescription (#PCDATA)>
        <!ELEMENT templateMetaData (type|template)*>
        <!ELEMENT type (#PCDATA)>
        <!ATTLIST type
                id ID #REQUIRED
                name CDATA #REQUIRED>
        ]>
<templateMetaData>
  <type id="callnarr" name="Call Narrative"/>
  <type id="normal" name="Generic Blank Narrative"/>
  <type id="normalcol" name="Generic Blank Narrative"/>
  <type id="cfa17o00" name="Monthly Assessment for Adoption"/>
  <type id="cfin01o00" name="CPS Intake Report"/>
  <type id="csc32o00" name="Child Life History"/>
  <type id="cpscnlsn" name="Investigation Conclusion"/>
  <type id="evalcncl" name="Evaluation Conclusion"/>
  <type id="fas03o00" name="Safety Plan Form"/>
  <type id="int01o00" name="Notification to L.E."/>
  <type id="fas01o00" name="Safety Assessment"/>
  <type id="fcm06o00" name="Service Authorization Form"/>
  <type id="fcm06o00v2" name="Service Authorization Referral Form"/>
  <type id="frd03o00" name="Home Evaluation Form"/>
  <type id="fel01o00" name="Foster Care Application"/>
  <type id="fel02o00" name="Reimbursabiliity Determination"/>
  <type id="frd01o00" name="Foster Care ReEvaluation"/>
  <type id="fcm01o00" name="Contact Visitation Log"/>
  <type id="cfsd0700" name="Log Of Contact Narratives"/>  
  <type id="fcm03o00" name="Diligent Search Report Form"/>
  <type id="fcm02o00" name="Visitation Plan Form"/>
  <type id="fcm05o00" name="Foster Care Plan Detail Form"/>
  <type id="fcm07o00" name="WTLP Form"/>
  <type id="leg01o00" name="Legal Actions Narrative"/>
  <type id="permroundtable" name="Permanency Round Table Form"/>
  <type id="safetyroundtable" name="Safety Roundtable Form"/>
  <type id="fim02o00" name="Mandated Reporter Letter Form"/>
  <type id="cvisitn" name="Contact Visitation Narrative"/>
  <type id="cvisitncol" name="Contact Visitation Narrative"/>
  <type id="fas05o00" name="Safety Resource Assessment"/>
  <type id="cfsd0500" name="Family Service Plan"/>
  <type id="fas02o00" name="Risk Assessment Form"/>
  <type id="teamnarr" name="Team Meeting Review Narrative"/>
  <type id="teamnarrong" name="Team Meeting Review Narrative for Ongoing"/>
  <type id="vstplnnarr" name="Visit Plan Narrative"/>
  <type id="cfa09o00" name="Policy Violation Report"/>
  <type id="cfa01o00" name="Corrective Action Plan"/>
  <type id="clhchklst" name="Child Life History Checklist"/>
  <type id="ado01o00" name="Special Services Adoption Assistance Agreement Form"/>
  <type id="adoassmem" name="Adoption Assistance Memorandum"/>
  <type id="adoassistagrmnt" name="Adoption Assistance Agreement"/>
  <type id="adodisruptnarr" name="Adoption Disruption Summary Narrative"/>
  <type id="fhconvnarr" name="Foster Home Conversion Narrative"/>
  <type id="spwbnarr" name="Safety, Permanency, Well Being Narrative"/>
  <type id="spwbnarrcol" name="Safety, Permanency, Well Being Narrative"/>
  <type id="scrnref" name="Screening And Referral Form"/> 
  <type id="respareq" name="Response to Case Review Request Form"/> 
  <type id="relativecare" name="Relative Care Assessment Form"/> 
  <type id="adminmemo" name="CPS Admistrative Review Decision Letter Form"/> 
  <type id="childdeath" name="Child Death Form"/>
  <type id="spwbnarrques" name="Safety, Permanency, Well Being Narrative Questions Form"/>
  <type id="spwbnarrguide" name="Safety, Permanency, Well Being Narrative Guide Form"/>
  <type id="mocallnarr" name="Call Narrative for Mobile"/>
  <type id="mocfin01o00" name="CPS Intake Report for Mobile"/>
  <type id="monormal" name="Generic Blank Narrative for Mobile"/>
  <type id="monormalcol" name="Generic Blank Narrative for Mobile"/>
  <type id="mocvisitn" name="Contact Visitation Narrative for Mobile"/>
  <type id="mocvisitncol" name="Contact Visitation Narrative for Mobile"/>
  <type id="mospwbnarr" name="Safety, Permanency, Well Being Narrative for Mobile"/>
  <type id="mospwbnarrcol" name="Safety, Permanency, Well Being Narrative for Mobile"/>
  <type id="rcsappagmt" name="Relative Care Subsidy Application and Agreement"/>
  <type id="nonrecuronlyaaagrmnt" name="Non-Recurring Only Adoption Assistance Agreement"/>
   
      
  <template type="callnarr" version="Call Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Call Narrative</shortDescription>
  </template>
  <template type="callnarr" version="Call Narrative" major="2" minor="0" revision="0" active="true">
    <shortDescription>Call Narrative</shortDescription>
    <longDescription>Call Narrative 2.0.0</longDescription>
  </template>  
  <template type="callnarr" version="Call Narrative" major="2" minor="1" revision="0" active="true">
    <shortDescription>Call Narrative</shortDescription>
    <longDescription>Call Narrative 2.1.0</longDescription>
  </template>    
  <template type="cfa17o00" version="Monthly Assessment for Adoption" major="1" minor="0" revision="0" active="true">
    <shortDescription>New HTML version converted from Word template</shortDescription>
  </template>
  <template type="cfin01o00" version="CPS Intake Report" major="1" minor="0" revision="0" active="true">
    <shortDescription>CPS Intake Report</shortDescription>
  </template>
  <template type="cpscnlsn" version="Investigation Conclusion" major="1" minor="0" revision="0" active="true">
    <shortDescription>Investigation Conclusion</shortDescription>
  </template>  
  <template type="csc32o00" version="Child Life History" major="1" minor="0" revision="0" active="true">
    <shortDescription>Child Life History Narrative 1.0.0</shortDescription>
  </template>
   <template type="permroundtable" version="Permanency Roundtable Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Permanency Roundtable Form</shortDescription>
    <longDescription>Permanency Roundtable Form 1.0.0</longDescription>
  </template>
  <template type="safetyroundtable" version="Safety Roundtable Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety Roundtable Form</shortDescription>
    <longDescription>Safety Roundtable Form 1.0.0</longDescription>
  </template>
  <template type="leg01o00" version="Legal Actions Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Legal Actions Narrative</shortDescription>
  </template>
  <template type="evalcncl" version="Evaluative Conclusion" major="1" minor="0" revision="0" active="true">
    <shortDescription>Evaluative Conclusion for FCE</shortDescription>
    <longDescription>Evaluative Conclusion for FCE</longDescription>
  </template>
  <template type="fas03o00" version="Safety Plan Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Facility Closing Summary</shortDescription>
  </template>
  <template type="fel01o00" version="Foster Care Application" major="1" minor="0" revision="0" active="false">
    <shortDescription>Foster Care Application</shortDescription>
    <longDescription>Foster Care Application 1.0.0</longDescription>
  </template>
  <template type="fel01o00" version="Foster Care Application" major="2" minor="0" revision="0" active="true">
    <shortDescription>Foster Care Application</shortDescription>
    <longDescription>Foster Care Application 2.0.0</longDescription>
  </template>
  <template type="int01o00" version="Notification to L.E." major="1" minor="0" revision="0" active="true">
    <shortDescription>Notification to L.E.</shortDescription>
    <longDescription>Notification to L.E.</longDescription>
  </template>
  <template type="normal" version="Generic Blank Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Generic Blank Narrative</shortDescription>
  </template>
  <template type="normalcol" version="Generic Blank Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Generic Blank Narrative</shortDescription>
  </template>
  <template type="fas01o00" version="Safety Assessment" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety Assessment</shortDescription>
  </template>
  <template type="fcm06o00" version="Service Authorization Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Service Authorization Form</shortDescription>
  </template>
  <template type="fcm06o00v2" version="Service Authorization Referral Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Service Authorization Referral Form</shortDescription>
    <longDescription>Service Authorization Referral Form 1.0.0</longDescription>   
  </template>
  <template type="fel02o00" version="Reimbursability Determination" major="1" minor="0" revision="0" active="false">
    <shortDescription>Reimbursability Determination</shortDescription>
    <longDescription>Reimbursability Determination 1.0.0</longDescription>
  </template>
  <template type="fel02o00" version="Reimbursability Determination" major="2" minor="0" revision="0" active="true">
    <shortDescription>Reimbursability Determination</shortDescription>
    <longDescription>Reimbursability Determination 2.0.0</longDescription>
  </template>
  <template type="frd03o00" version="Home Evaluation" major="1" minor="0" revision="0" active="true">
    <shortDescription>Home Evaluation</shortDescription>
    <longDescription>Resource Home Evaluation 1.0.0</longDescription>
  </template>
  <template type="frd01o00" version="Foster Care ReEvaluation" major="1" minor="0" revision="0" active="true">
    <shortDescription>Foster Care ReEvaluation</shortDescription>
    <longDescription>Foster Care ReEvaluation 1.0.0</longDescription>
  </template>
  <template type="fcm01o00" version="Contact Visitation Log" major="1" minor="0" revision="0" active="true">
    <shortDescription>Contact Visitation Log</shortDescription>
    <longDescription>Contact Visitation Log 1.0.0</longDescription>
  </template>
  <template type="cfsd0700" version="Log Of Contact Narratives" major="1" minor="0" revision="0" active="true">
    <shortDescription>Log Of Contact Narratives</shortDescription>
    <longDescription>Log Of Contact Narratives 1.0.0</longDescription>
  </template>  
  <template type="fcm03o00" version="Diligent Search Report Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Diligent Search Report Form</shortDescription>
    <longDescription>Diligent Search Report Form 1.0.0</longDescription>
  </template>
  <template type="fcm05o00" version="Foster Care Plan Detail Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Foster Care Plan Detail Form</shortDescription>
    <longDescription>Foster Care Plan Detail Form 1.0.0</longDescription>
  </template>
  <template type="fcm02o00" version="Visit Plan Form" major="2" minor="0" revision="0" active="true">
    <shortDescription>Visit Plan Form</shortDescription>
    <longDescription>Visit Plan Form 2.0.0</longDescription>
  </template>
  <template type="fcm05o00" version="Foster Care Plan Detail Form" major="1" minor="0" revision="1" active="true">
    <shortDescription>Foster Care Plan Detail Form</shortDescription>
    <longDescription>Foster Care Plan Detail Form 1.0.1</longDescription>
  </template>
  <template type="fim02o00" version="Mandated Reporter Letter Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Mandated Reporter Letter Form</shortDescription>
    <longDescription>Mandated Reporter Letter Form 1.0.0</longDescription>
  </template>
  <template type="cvisitn" version="Contact Visitation Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Contact Visitation Narrative</shortDescription>
    <longDescription>Contact Visitation Narrative 1.0.0</longDescription>
  </template>
  <template type="cvisitncol" version="Contact Visitation Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Contact Visitation Narrative</shortDescription>
    <longDescription>Contact Visitation Narrative 1.0.0</longDescription>
  </template>
  <template type="fas05o00" version="Safety Resource Assessment" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety Resource Assessment</shortDescription>
    <longDescription>Safety Resource Assessment 1.0.0</longDescription>
  </template>
  <template type="fas05o00" version="Safety Resource Assessment" major="2" minor="0" revision="0" active="true">
    <shortDescription>Safety Resource Assessment</shortDescription>
    <longDescription>Safety Resource Assessment 2.0.0</longDescription>
  </template>
  <template type="cfsd0500" version="Family Service Plan" major="1" minor="0" revision="0" active="true">
    <shortDescription>Family Service Plan</shortDescription>
    <longDescription>Family Service Plan</longDescription>
  </template>
  <template type="fas02o00" version="Risk Assessment Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Risk Assessment Form</shortDescription>
    <longDescription>Risk Assessment Form 1.0.0</longDescription>
  </template>
  <template type="teamnarr" version="Team Meeting Review Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Team Meeting Review Narrative</shortDescription>
    <longDescription>Team Meeting Review Narrative 1.0.0</longDescription>
  </template>
  <template type="teamnarrong" version="Team Meeting Review Narrative for Ongoing" major="1" minor="0" revision="0" active="true">
    <shortDescription>Team Meeting Review Narrative</shortDescription>
    <longDescription>Team Meeting Review Narrative 1.0.0</longDescription>
  </template>
  <template type="vstplnnarr" version="Visit Plan Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Visit Plan Narrative</shortDescription>
    <longDescription>Visit Plan Narrative 1.0.0</longDescription>
  </template>
  <template type="cfa09o00" version="Policy Violation Report" major="1" minor="0" revision="0" active="true">
    <shortDescription>Policy Violation Report</shortDescription>
    <longDescription>Policy Violation Report 1.0.0</longDescription>
  </template>  
  <template type="cfa01o00" version="Corrective Action Plan" major="1" minor="0" revision="0" active="true">
    <shortDescription>Corrective Action Plan</shortDescription>
    <longDescription>Corrective Action Plan 1.0.0</longDescription>
  </template>
  <template type="clhchklst" version="Child Life History Checklist" major="1" minor="0" revision="0" active="true">
    <shortDescription>Child Life History Checklist</shortDescription>
    <longDescription>Child Life History Checklist 1.0.0</longDescription>
  </template>        
    <template type="fcm07o00" version="WTLP Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>WTLP Form</shortDescription>
    <longDescription>WTLP Form 1.0.0</longDescription>
  </template>
    <template type="ado01o00" version="Special Services Adoption Assistance Agreement Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Special Services Adoption Assistance Agreement Form</shortDescription>
    <longDescription>Special Services Adoption Assistance Agreement Form 1.0.0</longDescription>
  </template>
  <template type="adoassmem" version="Adoption Assistance Memorandum" major="1" minor="0" revision="0" active="true">
    <shortDescription>Adoption Assistance Memorandum</shortDescription>
    <longDescription>Adoption Assistance Memorandum 1.0.0</longDescription>
  </template>  
  <template type="adoassistagrmnt" version="Adoption Assistance Agreement" major="1" minor="0" revision="0" active="true">
    <shortDescription>Adoption Assistance Agreement</shortDescription>
    <longDescription>Adoption Assistance Agreement 1.0.0</longDescription>
  </template>
  <template type="adodisruptnarr" version="Adoption Disruption Summary Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Adoption Disruption Summary Narrative</shortDescription>
    <longDescription>Adoption Disruption Summary Narrative 1.0.0</longDescription>   
  </template>
  <template type="fhconvnarr" version="Foster Home Conversion Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Foster Home Conversion Narrative</shortDescription>
    <longDescription>Foster Home Conversion Narrative 1.0.0</longDescription>   
  </template>
  <template type="spwbnarr" version="Safety, Permanency, Well Being Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Narrative</shortDescription>
    <longDescription>Safety, Permanency, Well Being Narrative 1.0.0</longDescription>   
  </template>   
  <template type="spwbnarr" version="Safety, Permanency, Well Being Narrative" major="1" minor="1" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Narrative</shortDescription>
    <longDescription>Safety, Permanency, Well Being Narrative 1.1.0</longDescription>   
  </template> 
  <template type="spwbnarr" version="Safety, Permanency, Well Being Guided Narrative" major="2" minor="0" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Guided Narrative</shortDescription>
    <longDescription>Safety, Permanency, Well Being Guided Narrative 2.0.0</longDescription>   
  </template>
  <template type="spwbnarrcol" version="Safety, Permanency, Well Being Guided Narrative" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Guided Narrative</shortDescription>
    <longDescription>Safety, Permanency, Well Being Guided Narrative 1.0.0</longDescription>   
  </template>
  <template type="scrnref" version="Screening And Referral Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Screening And Referral Form</shortDescription>
    <longDescription>Screening And Referral Form 1.0.0</longDescription>   
  </template>        
  <template type="respareq" version="Response to Case Review Request" major="1" minor="0" revision="0" active="true">
    <shortDescription>Response to Case Review Request Form</shortDescription>
    <longDescription>Response to Case Review Request Form 1.0.0</longDescription>   
  </template> 
  <template type="relativecare" version="Relative Care Assessment Form" major="1" minor="0" revision="0" active="true">
    <shortDescription>Relative Care Assessment Form</shortDescription>
    <longDescription>Relative Care Assessment Form 1.0.0</longDescription>   
  </template>        
  <template type="adminmemo" version="CPS Administrative Review Decision Letter" major="1" minor="0" revision="0" active="true">
    <shortDescription>CPS Administrative Review Decision Letter Form</shortDescription>
    <longDescription>CPS Administrative Review Decision Letter Form 1.0.0</longDescription>   
  </template>
  <template type="childdeath" version="Child Death Form" major="1" minor="0" revision="0" active="true">
  	<shortDescription>Child Death Form</shortDescription>
  	<longDescription>Child Death Form 1.0.0</longDescription>
  </template>
  <template type="spwbnarrques" version="Safety, Permanency, Well Being Interview Questions" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Interview Questions</shortDescription>
    <longDescription>Safety, Permanency, Well Being Interview Questions 1.0.0</longDescription>   
  </template>
  <template type="spwbnarrguide" version="Safety, Permanency, Well Being Narrative Guide" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Narrative Guide</shortDescription>
    <longDescription>Safety, Permanency, Well Being Narrative Guide 1.0.0</longDescription>   
  </template>
  <template type="mocallnarr" version="Call Narrative for Mobile" major="1" minor="0" revision="0" active="true">
    <shortDescription>Call Narrative</shortDescription>
  </template>
  <template type="mocallnarr" version="Call Narrative for Mobile" major="2" minor="0" revision="0" active="true">
    <shortDescription>Call Narrative</shortDescription>
    <longDescription>Call Narrative 2.0.0</longDescription>
  </template>  
  <template type="mocallnarr" version="Call Narrative for Mobile" major="2" minor="1" revision="0" active="true">
    <shortDescription>Call Narrative</shortDescription>
    <longDescription>Call Narrative 2.1.0</longDescription>
  </template>    
  <template type="monormal" version="Generic Blank Narrative for Mobile" major="1" minor="0" revision="0" active="true">
    <shortDescription>Generic Blank Narrative</shortDescription>
  </template>
  <template type="monormalcol" version="Generic Blank Narrative for Mobile" major="1" minor="0" revision="0" active="true">
    <shortDescription>Generic Blank Narrative</shortDescription>
  </template>
  <template type="mocfin01o00" version="CPS Intake Report for Mobile" major="1" minor="0" revision="0" active="true">
    <shortDescription>CPS Intake Report</shortDescription>
  </template>
  <template type="mocvisitn" version="Contact Visitation Narrative for Mobile" major="1" minor="0" revision="0" active="true">
    <shortDescription>Contact Visitation Narrative</shortDescription>
    <longDescription>Contact Visitation Narrative 1.0.0</longDescription>
  </template>
  <template type="mocvisitncol" version="Contact Visitation Narrative for Mobile" major="1" minor="0" revision="0" active="true">
    <shortDescription>Contact Visitation Narrative</shortDescription>
    <longDescription>Contact Visitation Narrative 1.0.0</longDescription>
  </template>
  <template type="mospwbnarr" version="Safety, Permanency, Well Being Narrative for Mobile" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Narrative</shortDescription>
    <longDescription>Safety, Permanency, Well Being Narrative 1.0.0</longDescription>   
  </template>   
  <template type="mospwbnarr" version="Safety, Permanency, Well Being Narrative for Mobile" major="1" minor="1" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Narrative</shortDescription>
    <longDescription>Safety, Permanency, Well Being Narrative 1.1.0</longDescription>   
  </template> 
  <template type="mospwbnarr" version="Safety, Permanency, Well Being Guided Narrative for Mobile" major="2" minor="0" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Guided Narrative</shortDescription>
    <longDescription>Safety, Permanency, Well Being Guided Narrative 2.0.0</longDescription>   
  </template>
  <template type="mospwbnarrcol" version="Safety, Permanency, Well Being Guided Narrative for Mobile" major="1" minor="0" revision="0" active="true">
    <shortDescription>Safety, Permanency, Well Being Guided Narrative</shortDescription>
    <longDescription>Safety, Permanency, Well Being Guided Narrative 1.0.0</longDescription>   
  </template>
  <template type="rcsappagmt" version="Relative Care Subsidy Application and Agreement" major="1" minor="0" revision="0" active="true">
    <shortDescription>Relative Care Subsidy Application and Agreement</shortDescription>
    <longDescription>Relative Care Subsidy Application and Agreement 1.0.0</longDescription>   
  </template>
  <template type="nonrecuronlyaaagrmnt" version="Non-Recurring Only Adoption Assistance Agreement" major="1" minor="0" revision="0" active="true">
    <shortDescription>Non-Recurring Only Adoption Assistance Agreement</shortDescription>
    <longDescription>Non-Recurring Only Adoption Assistance Agreement 1.0.0</longDescription>   
  </template>
</templateMetaData>
